version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: nodeblogdb
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - dbdata:/data/db
  redisdb:
    image: redis 
    container_name: redisdb 
    ports:
      - ${REDIS_PORT}:6379

volumes:
  dbdata: